name = "fitlife"
compatibility_date = "2025-04-27"

[site]
bucket = "dist"

[build]
command = "npm run build"
upload.format = "directory"

[env.production]
name = "fitlife"

[site.production]
bucket = "dist"