// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://allyzqfvkargtpdwwcje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsbHl6cWZ2a2FyZ3RwZHd3Y2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNDQ5NDgsImV4cCI6MjA1ODYyMDk0OH0.YA_g_VKhaLBRk89vJ2C4UjSMUsVn7u7jxQKRrsem11o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);